CREATE OR REPLACE TABLE PORTFOLIO_DE.RAW.store_sales AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES
LIMIT 200000;  -- biar cepat dan hemat

CREATE OR REPLACE TABLE PORTFOLIO_DE.RAW.date_dim AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM;

CREATE OR REPLACE TABLE PORTFOLIO_DE.RAW.item AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM;
